# Generated by Django 4.1.7 on 2023-07-31 05:06

import ARVappApi.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.UUIDField(default=ARVappApi.models.new_uuid, editable=False, primary_key=True, serialize=False)),
                ('projectType', models.CharField(max_length=50)),
                ('triggerType', models.CharField(max_length=50)),
                ('imagePro', models.FileField(blank=True, null=True, upload_to='image')),
                ('ProTitle', models.CharField(default='Untitled', max_length=255, null=True)),
                ('projectIcon', models.FileField(blank=True, null=True, upload_to='image')),
                ('projectTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('publish_key', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('dateofbirth', models.DateField()),
                ('proffession', models.TextField(choices=[('I am a Designer.', 'I am a Designer.'), ('I am a Developer.', 'I am a Developer.'), ('I am a Marketer.', 'I am a Marketer.'), ('I am a Educator.', 'I am a Educator.'), ('I am a 3D Artist.', 'I am a 3D Artist.'), ('I am working in Learning and Development.', 'I am working in Learning and Development.'), ('Something Else.', 'Something Else.')], max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_ID_QR_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id_qr_code_url', models.URLField()),
                ('qr_code_url', models.URLField()),
                ('publish_key', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARVappApi.createproject')),
            ],
        ),
        migrations.CreateModel(
            name='Project3DModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model3D', models.FileField(upload_to='3Dmodel')),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARVappApi.createproject')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARVappApi.video')),
            ],
        ),
        migrations.AddField(
            model_name='createproject',
            name='projectUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
