# Generated by Django 4.1.7 on 2023-08-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARVappApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_label', models.CharField(blank=True, max_length=250, null=True)),
                ('projectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ARVappApi.createproject')),
            ],
        ),
    ]
