# Generated by Django 4.1.7 on 2023-08-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARVappApi', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproject',
            name='imagePro',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='createproject',
            name='projectIcon',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
