# Generated by Django 4.1.7 on 2023-08-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARVappApi', '0006_alter_createproject_imagepro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZPT_Trained_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ZPT_File/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARVappApi.createproject')),
            ],
        ),
    ]
