# Generated by Django 4.1.7 on 2023-08-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARVappApi', '0009_testzpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestZPT',
        ),
    ]
