# Generated by Django 4.1.7 on 2023-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARVappApi', '0010_delete_testzpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpt_trained_model',
            name='file',
        ),
        migrations.AddField(
            model_name='zpt_trained_model',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
